# Examples of the pyrankability package

In [6]:
from IPython.core.display import display, HTML
import pandas as pd
import numpy as np
import copy
import os
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
import sys
sys.path.insert(0,"/local/rankability_toolbox")

In [8]:
import pyrankability

In [9]:
PATH_TO_RANKLIB='/local/ranklib'

In [10]:
from numpy import ix_
import numpy as np

D = np.loadtxt(PATH_TO_RANKLIB+"/problem_instances/instances/graphs/NFL-2007-D_Matrix.txt",delimiter=",")

Dsmall = D[ix_(np.arange(8),np.arange(8))]
Dsmall

array([[0., 0., 1., 1., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

## Dask supported algorithms

At the terminal, you cna run the following:

<pre>
dask-scheduler > /var/log/scheduler.log 2>&1 &

dask-worker > /var/log/worker.log localhost:8786 2>&1 &
</pre>

For more details, please see [https://dask.org/](https://dask.org/)

### Test Dask Code
Run the code below to make sure everything works correctly in your environment.

In [11]:
from dask.distributed import Client

import json
import itertools

client = Client("127.0.0.1:8786")

futures = client.map(lambda x: x+1, [0,1,2,3])
results = client.gather(futures)
print(results)

[1, 2, 3, 4]


## Parallel exhaustive search

In [7]:
search = pyrankability.exact.ExhaustiveSearch(Dsmall)
search.find_P()

print(pyrankability.common.as_json(search.k,search.P,{}))

{"k": 17, "p": 3, "P": [[1, 3, 7, 4, 5, 2, 6, 8], [1, 7, 3, 4, 5, 2, 6, 8], [1, 7, 4, 3, 5, 2, 6, 8]], "other": {}}


## Parallel Pruning Search

In [12]:
np.savetxt("/dev/shm/D.csv",Dsmall,delimiter=",",fmt="%d")

In [31]:
k,p,P = pyrankability.pruning_paper_dask3.find_P("/dev/shm/Dsmall.csv",4,100,bilp_method="orig",client=client)

In [33]:
P

[[0, 6, 3, 2, 4, 1, 5, 7], [0, 6, 2, 3, 4, 1, 5, 7], [0, 2, 6, 3, 4, 1, 5, 7]]

In [5]:
from numpy import ix_

Dsmall = D[ix_(np.arange(8),np.arange(8))]
Dsmall

array([[0., 0., 1., 1., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
k, P, skipped = pyrankability.pruning_paper_dask2.find_P(,4,100,bilp_method="orig")

SyntaxError: invalid syntax (<ipython-input-30-3037721b78db>, line 1)

In [53]:
k,P,skipped

(17,
 [[0, 2, 6, 3, 4, 1, 5, 7],
  [0, 6, 2, 3, 4, 1, 5, 7],
  [0, 6, 3, 2, 4, 1, 5, 7]],
 36504)

In [57]:
import math 
percent_skipped = skipped*1./math.factorial(Dsmall.shape[0])
percent_skipped

0.9053571428571429

In [30]:
old_code_method = pyrankability.exact.RecusiveKBoundedSearch(Dsmall)
old_code_method.find_P()

In [31]:
old_code_method.k,old_code_method.P

(17.0,
 [(0, 2, 6, 3, 4, 1, 5, 7),
  (0, 6, 2, 3, 4, 1, 5, 7),
  (0, 6, 3, 2, 4, 1, 5, 7)])

In [ ]:
P_to_search = large_problem_solver.P_to_search

In [ ]:
large_problem_solver.find_P()

In [158]:
len(large_problem_solver.P[0])

32

In [144]:
large_problem_solver.find_P()

Number of new solutions added: 111
Number of new solutions added: 22
Number of new solutions added: 0
Number of new solutions added: 55


188

In [153]:
len(large_problem_solver.P_to_search)

95

In [152]:
len(large_problem_solver.P)

368

In [155]:
large_problem_solver.P_searched

{(20,
  11,
  0,
  8,
  13,
  6,
  3,
  2,
  14,
  15,
  16,
  26,
  21,
  4,
  1,
  22,
  19,
  5,
  28,
  10,
  29,
  25,
  12,
  23,
  17,
  27,
  7,
  9,
  24,
  18,
  30,
  31): 1}

In [49]:
Psolution

array([11,  0, 13, 26,  8,  2,  6,  3, 20, 21, 14, 15,  4,  1, 22, 16, 10,
       25, 12, 23, 19,  5, 17, 28, 27,  7,  9, 24, 18, 30, 31, 29])

In [50]:
subset

array([11,  0, 13, 26,  8,  2,  6,  3, 20, 21])

In [52]:
global_D = pyrankability.permute_D(D,Psolution)
print(pyrankability.calc_k(global_D))

394.0


In [53]:
global_sol_k = k
global_sol_k

394

True

In [63]:
kspec = pyrankability.calc_k(Dspec)
solution = find_P(Dspec,1000,4,global_sol_k,Dspec.shape[0],10,(),num_parallel=18,client=None)

46.0

In [87]:
global_inxs,solution[1][0]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), (0, 1, 2, 3, 4, 5, 6, 7, 8, 9))

In [98]:
import copy



In [102]:
Pdf_new = pd.DataFrame(P+new_solutions)
Pdf_new.drop_duplicates(inplace=True)

In [103]:
Pdf_new.shape

(635, 32)

In [104]:
Pdf.shape

(93, 32)

In [80]:
global_inxs[np.array(local_solution)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
local_solution

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)