In [1]:
from IPython.core.display import display, HTML
import pandas as pd
import numpy as np
import copy
import os
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append("..")

In [3]:
import numpy as np
from dask.distributed import Client

import pyrankability

import json
import itertools

client = Client("127.0.0.1:8786")

D = np.loadtxt("../../ranklib/problem_instances/instances/graphs/NFL-2007-D_Matrix.txt",delimiter=",")

In [4]:
from numpy import ix_

In [5]:
Dsmall = D[ix_(np.arange(8),np.arange(8))]
Dsmall

array([[0., 0., 1., 1., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
k, P, skipped = pyrankability.pruning_paper.find_P(Dsmall,4,100)

In [53]:
k,P,skipped

(17,
 [[0, 2, 6, 3, 4, 1, 5, 7],
  [0, 6, 2, 3, 4, 1, 5, 7],
  [0, 6, 3, 2, 4, 1, 5, 7]],
 36504)

In [57]:
import math 
percent_skipped = skipped*1./math.factorial(Dsmall.shape[0])
percent_skipped

0.9053571428571429

In [30]:
old_code_method = pyrankability.exact.RecusiveKBoundedSearch(Dsmall)
old_code_method.find_P()

In [31]:
old_code_method.k,old_code_method.P

(17.0,
 [(0, 2, 6, 3, 4, 1, 5, 7),
  (0, 6, 2, 3, 4, 1, 5, 7),
  (0, 6, 3, 2, 4, 1, 5, 7)])

In [ ]:
P_to_search = large_problem_solver.P_to_search

In [ ]:
large_problem_solver.find_P()

In [158]:
len(large_problem_solver.P[0])

32

In [144]:
large_problem_solver.find_P()

Number of new solutions added: 111
Number of new solutions added: 22
Number of new solutions added: 0
Number of new solutions added: 55


188

In [153]:
len(large_problem_solver.P_to_search)

95

In [152]:
len(large_problem_solver.P)

368

In [155]:
large_problem_solver.P_searched

{(20,
  11,
  0,
  8,
  13,
  6,
  3,
  2,
  14,
  15,
  16,
  26,
  21,
  4,
  1,
  22,
  19,
  5,
  28,
  10,
  29,
  25,
  12,
  23,
  17,
  27,
  7,
  9,
  24,
  18,
  30,
  31): 1}

In [49]:
Psolution

array([11,  0, 13, 26,  8,  2,  6,  3, 20, 21, 14, 15,  4,  1, 22, 16, 10,
       25, 12, 23, 19,  5, 17, 28, 27,  7,  9, 24, 18, 30, 31, 29])

In [50]:
subset

array([11,  0, 13, 26,  8,  2,  6,  3, 20, 21])

In [52]:
global_D = pyrankability.permute_D(D,Psolution)
print(pyrankability.calc_k(global_D))

394.0


In [53]:
global_sol_k = k
global_sol_k

394

True

In [63]:
kspec = pyrankability.calc_k(Dspec)
solution = find_P(Dspec,1000,4,global_sol_k,Dspec.shape[0],10,(),num_parallel=18,client=None)

46.0

In [87]:
global_inxs,solution[1][0]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), (0, 1, 2, 3, 4, 5, 6, 7, 8, 9))

In [98]:
import copy



In [102]:
Pdf_new = pd.DataFrame(P+new_solutions)
Pdf_new.drop_duplicates(inplace=True)

In [103]:
Pdf_new.shape

(635, 32)

In [104]:
Pdf.shape

(93, 32)

In [80]:
global_inxs[np.array(local_solution)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
local_solution

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)