In [139]:
import sys

In [140]:
sys.path.append("/home/panderson/rankability_toolbox")

In [141]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [142]:
import itertools

In [143]:
import numpy as np

In [144]:
import pyrankability

In [7]:
D=np.array([[0,0,0,0,1,19,0,0],
[7,0,21,24,23,29,0,0],
[20,0,0,14,0,18,7,11],
[5,0,0,0,3,21,0,0],
[0,0,7,0,0,30,0,32],
[0,0,0,0,0,0,0,3],
[6,3,0,45,22,38,0,0],
[3,14,0,14,0,0,14,0]])

In [9]:
D

array([[ 0,  0,  0,  0,  1, 19,  0,  0],
       [ 7,  0, 21, 24, 23, 29,  0,  0],
       [20,  0,  0, 14,  0, 18,  7, 11],
       [ 5,  0,  0,  0,  3, 21,  0,  0],
       [ 0,  0,  7,  0,  0, 30,  0, 32],
       [ 0,  0,  0,  0,  0,  0,  0,  3],
       [ 6,  3,  0, 45, 22, 38,  0,  0],
       [ 3, 14,  0, 14,  0,  0, 14,  0]])

In [21]:
k,details = pyrankability.hillside.count_lp(D)

In [23]:
details["P"]

[[0, 1, 2, 3, 4, 5, 6, 7], [1, 0, 2, 3, 4, 5, 6, 7]]

In [26]:
D=np.array([[0,0,0,18,12,0,35,0,0],
[21,0,10,3,0,0,41,0,14],
[18,0,0,10,0,0,4,4,8],
[0,0,0,0,23,0,2,4,3],
[0,21,20,0,0,0,0,9,13],
[38,1,27,21,3,0,48,3,14],
[0,0,0,0,3,0,0,0,0],
[3,7,0,0,0,0,10,0,30],
[1,0,0,0,0,0,25,0,0]])
D

array([[ 0,  0,  0, 18, 12,  0, 35,  0,  0],
       [21,  0, 10,  3,  0,  0, 41,  0, 14],
       [18,  0,  0, 10,  0,  0,  4,  4,  8],
       [ 0,  0,  0,  0, 23,  0,  2,  4,  3],
       [ 0, 21, 20,  0,  0,  0,  0,  9, 13],
       [38,  1, 27, 21,  3,  0, 48,  3, 14],
       [ 0,  0,  0,  0,  3,  0,  0,  0,  0],
       [ 3,  7,  0,  0,  0,  0, 10,  0, 30],
       [ 1,  0,  0,  0,  0,  0, 25,  0,  0]])

In [119]:
k,details = pyrankability.hillside.count_lp(D)
k,details

[0 3 7 5 1 2 6 4]


(154,
 {'x': array([[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
         [2.26114683e-11, 1.00000000e+00, 5.00985101e-01, 5.57709187e-11,
          9.99999963e-01, 9.11356041e-10, 1.00000000e+00, 4.90648750e-10],
         [2.22069030e-11, 4.99014899e-01, 1.00000000e+00, 3.20329736e-11,
          9.99999963e-01, 7.84071071e-10, 9.99999999e-01, 2.77786100e-11],
         [3.73525766e-10, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 5.97121933e-01],
         [2.00451877e-11, 3.72340434e-08, 3.65647091e-08, 6.64728272e-11,
          1.00000000e+00, 7.00390214e-11, 3.72993197e-08, 5.65432269e-11],
         [6.52436993e-11, 9.99999999e-01, 9.99999999e-01, 1.16271548e-10,
          1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 3.99427238e-01],
         [2.32263098e-11, 4.20954827e-10, 9.07128594e-10, 3.84499099e-11,
          9.99999963e

In [145]:
import pandas as pd

D = pd.read_csv("~/rankabilitylib-data/college_football/MBB/PatriotLeague/2008d1Matrix.csv",header=None).values
D

array([[ 0., 34.,  4., 22., 18., 23., 25.,  0.],
       [ 0.,  0., 19.,  2., 14.,  5.,  3.,  2.],
       [ 4.,  0.,  0., 10.,  8.,  2.,  0.,  9.],
       [ 0.,  6., 14.,  0., 20.,  3.,  8., 18.],
       [ 2., 11., 10.,  0.,  0., 20., 18.,  0.],
       [ 0., 25., 12.,  1.,  8.,  0., 18.,  4.],
       [ 0., 10., 13.,  3.,  7.,  5.,  0.,  0.],
       [26.,  8.,  6.,  0., 17.,  2., 15.,  0.]])

In [146]:
D

array([[ 0., 34.,  4., 22., 18., 23., 25.,  0.],
       [ 0.,  0., 19.,  2., 14.,  5.,  3.,  2.],
       [ 4.,  0.,  0., 10.,  8.,  2.,  0.,  9.],
       [ 0.,  6., 14.,  0., 20.,  3.,  8., 18.],
       [ 2., 11., 10.,  0.,  0., 20., 18.,  0.],
       [ 0., 25., 12.,  1.,  8.,  0., 18.,  4.],
       [ 0., 10., 13.,  3.,  7.,  5.,  0.,  0.],
       [26.,  8.,  6.,  0., 17.,  2., 15.,  0.]])

In [166]:
k,details = pyrankability.hillside.count_lp(D)
k,details

(154,
 {'x': array([[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
         [2.26114683e-11, 1.00000000e+00, 5.00985101e-01, 5.57709187e-11,
          9.99999963e-01, 9.11356041e-10, 1.00000000e+00, 4.90648750e-10],
         [2.22069030e-11, 4.99014899e-01, 1.00000000e+00, 3.20329736e-11,
          9.99999963e-01, 7.84071071e-10, 9.99999999e-01, 2.77786100e-11],
         [3.73525766e-10, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 5.97121933e-01],
         [2.00451877e-11, 3.72340434e-08, 3.65647091e-08, 6.64728272e-11,
          1.00000000e+00, 7.00390214e-11, 3.72993197e-08, 5.65432269e-11],
         [6.52436993e-11, 9.99999999e-01, 9.99999999e-01, 1.16271548e-10,
          1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 3.99427238e-01],
         [2.32263098e-11, 4.20954827e-10, 9.07128594e-10, 3.84499099e-11,
          9.99999963e

In [16]:
pyrankability.hillside.objective_count_exhaustive(D)

(155,
 {'P': [(4, 6, 1, 2, 5, 3, 7, 0),
   (4, 6, 1, 2, 5, 7, 3, 0),
   (4, 6, 1, 2, 7, 5, 3, 0),
   (4, 6, 2, 1, 5, 3, 7, 0),
   (4, 6, 2, 1, 5, 7, 3, 0),
   (4, 6, 2, 1, 7, 5, 3, 0)]})

In [118]:
[1,2,3][::-1]

[3, 2, 1]

{(4, 6, 1, 2, 3, 5, 7, 0),
 (4, 6, 1, 2, 3, 7, 5, 0),
 (4, 6, 1, 2, 5, 3, 7, 0),
 (4, 6, 1, 2, 5, 7, 3, 0),
 (4, 6, 1, 2, 7, 3, 5, 0),
 (4, 6, 1, 2, 7, 5, 3, 0),
 (4, 6, 2, 1, 3, 5, 7, 0),
 (4, 6, 2, 1, 3, 7, 5, 0),
 (4, 6, 2, 1, 5, 3, 7, 0),
 (4, 6, 2, 1, 5, 7, 3, 0),
 (4, 6, 2, 1, 7, 3, 5, 0),
 (4, 6, 2, 1, 7, 5, 3, 0)}

In [163]:
for perm in P:
    pyrankability.hillside.objective_count_perm(D,perm))

155
160
160
160
155
155
155
160
155
160
160
155
